### Load packages and input data

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Boder_transcripts_clean.csv")

### Data Manipulation

#### Change the data type of id_new and fill the NAs

In [8]:
# Reference: https://stackoverflow.com/questions/41212273/pandaspython-fill-empty-cells-with-with-previous-row-value
# the empty number should be the same as the closest non-empty number above
df.id_new = df.id_new.fillna(method='ffill')

In [12]:
df.id_new = df.id_new.apply(lambda x: int(x))

In [15]:
df.id_new.isna().sum()

0

#### Create columns like the Holocaust format
Do not `delet` but `add`

In [16]:
df["file_cat"]=["Boder"]*len(df)

In [20]:
df["que_ans"]=[np.nan]*len(df)

In [23]:
# if speaker is David Boder, is could be a question
# categorize it as 0
# all answers, by other people, are 1
df.que_ans = df.speaker.apply(lambda x: 0 if x=="David Boder" else 1)
# if there is no question mark in David Boder's lines
# change them into 3
for i in range(len(df)):
    if (df.que_ans[i]==0 and '?' not in df.words[i]):
        df.que_ans[i]= 3

/Users/lizhoufan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


Further question:
Segment standard? We can only link the page wiht the Boder Index; we cannot link the time segment.

### Which two transcrpts are not linked?
I encoded the id_new for unmatched ones as 0. Just find from 1-118 in Boder data, which two are missing, and then match them, if possible.

In [40]:
set(df[df.id_new==0].id_old) # id_old are 9, 108, and 109

{9, 108, 109, 110}

Chnged two mistakes of marking 0 for 74 manually.

In [41]:
set(df[df.id_new!=0].id_new) # id_new missing ones are 10, 18, 92, 96

{1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 93,
 94,
 95,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118}

I found that:
- id_old = 9 could be id_new=10, Borgman. I missed this because this interview also includes large proportion by Joseph Freinhoffer, who is not in our meta list.
- id_old = 109 could be id_new = 18, Deutsch. I missed this because the first names of this person are quite different for the English and non-English spellings.
- id_new = 92 was missed writtten as 91. Rudo.
- id_old = 108 could be id_new = 96, Schrameck Abraham. I missed this because this interview also includes large proportion by Joseph Freinhoffer, who is is already categorized in other parts.

### Export Data

In [25]:
df.to_csv("Boder_transcripts_clean_manipulated.csv", index=False)

Then manully change the numbers according to which two documents are not linked.

Cleaned data: https://docs.google.com/spreadsheets/d/1CExHtiXaLzd7zKau_DDOQqyxffnve61HtR6TlgB7uk0/edit#gid=569865206